#define ELF_TARG_CLASS ELFCLASS64
#if __BYTE_ORDER__ == __ORDER_LITTLE_ENDIAN__
#define ELF_TARG_DATA ELFDATA2LSB
#else
#define ELF_TARG_DATA ELFDATA2MSB
#endif
#define ELF_TARG_MACH EM_AARCH64
#define ELF_TARG_VER 1
